# Generated by Django 4.2.13 on 2024-07-09 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='admin_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='birth_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='certificates_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='highschool_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='secondary_school_certificate',
            field=models.BooleanField(default=False),
        ),
    ]
