# Generated by Django 4.2.13 on 2024-07-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_admin_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='admin_comments',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='notified',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='secondary_school_certificate',
        ),
        migrations.AddField(
            model_name='submission',
            name='secondary_certificate',
            field=models.FileField(blank=True, null=True, upload_to='static/images/certificates/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='static/images/certificates/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='highschool_certificate',
            field=models.FileField(blank=True, null=True, upload_to='static/images/certificates/'),
        ),
    ]
