# Generated by Django 4.2.13 on 2024-07-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_alter_submission_birth_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
